# Generated by Django 3.1.6 on 2021-09-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_notional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_class',
            field=models.CharField(choices=[('simple', 'simple'), ('bracket', 'bracket'), ('oco', 'one cancels other'), ('oto', 'one triggers other')], default='simple', max_length=56, verbose_name='order class'),
        ),
    ]
