# Generated by Django 3.1.6 on 2021-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trail_percentage',
        ),
        migrations.AddField(
            model_name='order',
            name='trail_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='trail percent'),
        ),
    ]
