# Generated by Django 3.1.3 on 2020-11-23 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_tradable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.assetclass', verbose_name='asset class'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.exchange', verbose_name='exchange'),
        ),
    ]
