# Generated by Django 3.1.3 on 2020-11-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_foreign_key_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=56, verbose_name='status'),
        ),
    ]
