# Generated by Django 3.1.3 on 2020-11-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_name_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetclass',
            old_name='is_current',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='is_current',
            new_name='is_active',
        ),
    ]
