# Generated by Django 3.1.3 on 2020-12-01 06:11

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_rename_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=56, unique=True, verbose_name='symbol'),
        ),
    ]
