# Generated by Django 3.1.3 on 2020-12-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_symbol_case_insensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetclass',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='name'),
        ),
    ]
