# Generated by Django 3.1.3 on 2020-12-06 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_class_exchange_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59a4a08a-4944-42a3-a9a9-18f803772b97'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
