# Generated by Django 3.1.2 on 2020-11-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('alt_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='alt name')),
                ('is_current', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'asset class',
                'verbose_name_plural': 'asset classes',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], max_length=56, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetclass', verbose_name='asset class'),
        ),
    ]
