# Generated by Django 3.1.2 on 2020-11-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_add_asset_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='tradeable',
            new_name='tradable',
        ),
    ]
