# Generated by Django 3.1.3 on 2020-12-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='type',
            field=models.CharField(choices=[('moving_average_14d', '14 day moving average'), (
                'moving_average_7d', '7 day moving average')], max_length=128, verbose_name='type'),
        ),
    ]
