# Generated by Django 3.1.3 on 2021-01-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='timeframe',
            field=models.CharField(choices=[('1Min', '1 minute'), ('5Min', '5 minute'), ('15Min', '15 minute'), ('1H', '1 hour'), ('1D', '1 day')], default='15Min', max_length=128, verbose_name='timeframe'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='type',
            field=models.CharField(choices=[('moving_average_14d', '14 day moving average'), ('moving_average_7d', '7 day moving average')], max_length=128, verbose_name='type'),
        ),
    ]
